################################################################################
# Fichier de test des routes HTTP de l'API
# Nécessite l'extension REST Client pour VSCode
# https://marketplace.visualstudio.com/items?itemName=humao.rest-client
################################################################################
@endpoint = http://localhost:{{$dotenv PORT}}/v1/api

########################################################
#                         API                          #
########################################################

#########################
#        ALL            #
#########################

###
GET {{ endpoint }}/
###
POST {{ endpoint }}/
###
PUT {{ endpoint }}/
###
PATCH {{ endpoint }}/
###
DELETE {{ endpoint }}/

### Erreur
GET {{ endpoint }}/sadgdafh

### test
GET {{ endpoint }}/test

#########################
#        Common         #
#########################

### get all constellations
GET {{ endpoint }}/common/constellation

### TEST d'ERREUR
GET {{ endpoint }}/common/sdfsqdgsdg

### get one constellation
GET {{ endpoint }}/common/constellation/1


#########################
#      Constellation    #
#########################

### find one Constellation By Pk With Myths
GET {{ endpoint }}/constellation/1

#########################
#      Myth             #
#########################

### get one random Myth with constellation
GET {{ endpoint }}/myth/random

#########################
#      Geocoding        #
#########################

### Forward ERROR
GET {{ endpoint }}/geocoding/forward/?address=sdgqegezegzer

### Forward
GET {{ endpoint }}/geocoding/forward/?address=1600 Pennsylvania Ave NW, Washington DC

### Reverse
GET {{ endpoint }}/geocoding/reverse/?gps=40.7638435,-73.9729691

### Forward
GET {{ endpoint }}/geocoding/forward/?address=14 rue de Paradis, 75010 Paris

### Reverse
GET {{ endpoint }}/geocoding/forward/?address=Avenida Mariscal Santa Cruz 1066, La Paz