################################################################################
# Fichier de test des routes HTTP de l'API
# Nécessite l'extension REST Client pour VSCode
# https://marketplace.visualstudio.com/items?itemName=humao.rest-client
################################################################################
@endpoint = http://localhost:{{$dotenv PORT}}/v1/api/common

########################################################
#                         Common                       #
########################################################

### get all constellations
GET {{ endpoint }}/constellation

### TEST d'ERREUR
GET {{ endpoint }}/sdfsqdgsdg

### get one constellation
GET {{ endpoint }}/constellation/1

### insert a user
POST {{ endpoint }}/user
content-type: application/json

{
    "firstname": "Marceline",
    "lastname": "Ajun",
    "email": "marcelineajun@gmail.com",
    "password": "xxxx",
    "role": "user",
    "notification": true
}

### update a user
PATCH {{ endpoint }}/user
Authorization:Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJjbGVhbmVkVXNlciI6eyJpZCI6MjMsImZpcnN0bmFtZSI6Ik1hcmNlbGluZSIsImxhc3RuYW1lIjoiQWp1biIsImVtYWlsIjoibWFyY2VsaW5lYWp1bkBnbWFpbC5jb20iLCJyb2xlIjoidXNlciIsIm5vdGlmaWNhdGlvbiI6dHJ1ZX0sImlhdCI6MTY0OTU4MTEzNSwiZXhwIjoxNjQ5NjY3NTM1fQ.t6BMgeR2qOQruzoKE5xIwRMTLVsck-Z2PLtOjdS4k-c
content-type: application/json

{
    "firstname": "Marceline",
    "lastname": "Ajun",
    "email": "marcelineajun@gmail.com",
    "oldPassword": "xxxx",
    "newPassword": "yyyy",
    "role": "user",
    "notification": true
}
