################################################################################
# Fichier de test des routes HTTP de l'API
# Nécessite l'extension REST Client pour VSCode
# https://marketplace.visualstudio.com/items?itemName=humao.rest-client
################################################################################
@endpoint = http://localhost:{{$dotenv PORT}}/v1/api/common

########################################################
#                         Common                       #
########################################################

### get all constellations
GET {{ endpoint }}/constellation

### TEST d'ERREUR
GET {{ endpoint }}/sdfsqdgsdg

### get one constellation
GET {{ endpoint }}/constellation/1

### insert a user
POST {{ endpoint }}/user
content-type: application/json

{
    "firstname": "g",
    "lastname": "v",
    "email": "gv@gmail.com",
    "password": "xx",
    "role": "user",
    "notification": true
}

### Update something (not user)
PATCH {{ endpoint }}/place/2
Authorization:Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJjbGVhbmVkVXNlciI6eyJpZCI6MjgsImZpcnN0bmFtZSI6ImciLCJsYXN0bmFtZSI6InYiLCJlbWFpbCI6Imd2QGdtYWlsLmNvbSIsInJvbGUiOiJ1c2VyIiwibm90aWZpY2F0aW9uIjp0cnVlfSwiaWF0IjoxNjQ5NjgxMjY5LCJleHAiOjE2NDk3Njc2Njl9.HOl7OGNrgCZq2jCHtqL1nATJeofSZEVj-jiBGeGdfzo
content-type: application/json

{
    "name": "PoisonIvyIII",
    "address": "68298 Fairview Place",
    "city": "Huoqiu Chengguanzhen",
    "latitude": 32.331736,
    "longitude": 116.273391
}