################################################################################
# Fichier de test des routes HTTP de l'API
# Nécessite l'extension REST Client pour VSCode
# https://marketplace.visualstudio.com/items?itemName=humao.rest-client
################################################################################
@endpoint = http://localhost:{{$dotenv PORT}}/v1/api/constellation

########################################################
#                    Constellation                     #
########################################################

### Select one Constellation By Id with all attributes (myths, stars, galaxies)
GET {{ endpoint }}/87

### Select all Constellations with all attributes (myths, stars, galaxies)
GET {{ endpoint }}/

### Select all Constellations names
GET {{ endpoint }}/names

### Insert favorite constellation
POST {{ endpoint }}/favorite
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjo5LCJmaXJzdG5hbWUiOiJ5IiwibGFzdG5hbWUiOiJ5IiwiZW1haWwiOiJ5eUBnbWFpbC5jb20iLCJyb2xlIjoidXNlciIsIm5vdGlmaWNhdGlvbiI6dHJ1ZX0sImlhdCI6MTY1MDMxMDc0NSwiZXhwIjoxNjUwMzk3MTQ1fQ.CeGANCiVPPyeg0-hg-_In8HpCQFunbNsXheXlkGBSEw

{
    "constellation_id": 87
}

### Select All favorites constellations
GET {{ endpoint }}/favorite
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjo5LCJmaXJzdG5hbWUiOiJ5IiwibGFzdG5hbWUiOiJ5IiwiZW1haWwiOiJ5eUBnbWFpbC5jb20iLCJyb2xlIjoidXNlciIsIm5vdGlmaWNhdGlvbiI6dHJ1ZX0sImlhdCI6MTY1MDMxMDc0NSwiZXhwIjoxNjUwMzk3MTQ1fQ.CeGANCiVPPyeg0-hg-_In8HpCQFunbNsXheXlkGBSEw

### Delete favorite constellation
DELETE {{ endpoint }}/favorite/87
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjo5LCJmaXJzdG5hbWUiOiJ5IiwibGFzdG5hbWUiOiJ5IiwiZW1haWwiOiJ5eUBnbWFpbC5jb20iLCJyb2xlIjoidXNlciIsIm5vdGlmaWNhdGlvbiI6dHJ1ZX0sImlhdCI6MTY1MDMxMDc0NSwiZXhwIjoxNjUwMzk3MTQ1fQ.CeGANCiVPPyeg0-hg-_In8HpCQFunbNsXheXlkGBSEw