################################################################################
# Fichier de test des routes HTTP de l'API
# Nécessite l'extension REST Client pour VSCode
# https://marketplace.visualstudio.com/items?itemName=humao.rest-client
################################################################################
@endpoint = http://localhost:{{$dotenv PORT}}/v1/api/event

########################################################
#                         Event                        #
########################################################

### Insert un nouvel event
POST {{ endpoint }}/
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjo2LCJmaXJzdG5hbWUiOiJiIiwibGFzdG5hbWUiOiJiIiwiZW1haWwiOiJiYkBnbWFpbC5jb20iLCJyb2xlIjoidXNlciIsIm5vdGlmaWNhdGlvbiI6dHJ1ZX0sImlhdCI6MTY1MDI3OTMzMiwiZXhwIjoxNjUwMzY1NzMyfQ.4uKaBav0X0AyPZnkAkGIGwxnPUAf3WBASkGOi9BxI4o

{
    "name": "Soirée",
    "address": "Ariège",
    "event_datetime": "2022-05-12 07:19:12",
    "recall_datetime": "2022-05-11 23:00:00"
}

### Get all events of a user
GET {{ endpoint }}/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjo2LCJmaXJzdG5hbWUiOiJiIiwibGFzdG5hbWUiOiJiIiwiZW1haWwiOiJiYkBnbWFpbC5jb20iLCJyb2xlIjoidXNlciIsIm5vdGlmaWNhdGlvbiI6dHJ1ZX0sImlhdCI6MTY1MDIyMjY3NCwiZXhwIjoxNjUwMzA5MDc0fQ.7evXt4muqm-L8c64ACrhW-ZwEqTt-0cR-pmCGhaPrFs

### Get one event of a user
GET {{ endpoint }}/7
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjo2LCJmaXJzdG5hbWUiOiJiIiwibGFzdG5hbWUiOiJiIiwiZW1haWwiOiJiYkBnbWFpbC5jb20iLCJyb2xlIjoidXNlciIsIm5vdGlmaWNhdGlvbiI6dHJ1ZX0sImlhdCI6MTY1MDI3OTMzMiwiZXhwIjoxNjUwMzY1NzMyfQ.4uKaBav0X0AyPZnkAkGIGwxnPUAf3WBASkGOi9BxI4o

### Update an event of a user
PATCH {{ endpoint }}/7
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjo2LCJmaXJzdG5hbWUiOiJiIiwibGFzdG5hbWUiOiJiIiwiZW1haWwiOiJiYkBnbWFpbC5jb20iLCJyb2xlIjoidXNlciIsIm5vdGlmaWNhdGlvbiI6dHJ1ZX0sImlhdCI6MTY1MDI3OTMzMiwiZXhwIjoxNjUwMzY1NzMyfQ.4uKaBav0X0AyPZnkAkGIGwxnPUAf3WBASkGOi9BxI4o

{
    "name": "Chez Marc"
}

### Delete an event of a user
DELETE {{ endpoint }}/6
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjo2LCJmaXJzdG5hbWUiOiJiIiwibGFzdG5hbWUiOiJiIiwiZW1haWwiOiJiYkBnbWFpbC5jb20iLCJyb2xlIjoidXNlciIsIm5vdGlmaWNhdGlvbiI6dHJ1ZX0sImlhdCI6MTY1MDIyMjY3NCwiZXhwIjoxNjUwMzA5MDc0fQ.7evXt4muqm-L8c64ACrhW-ZwEqTt-0cR-pmCGhaPrFs