################################################################################
# Fichier de test des routes HTTP de l'API
# Nécessite l'extension REST Client pour VSCode
# https://marketplace.visualstudio.com/items?itemName=humao.rest-client
################################################################################
@endpoint = http://localhost:{{$dotenv PORT}}/v1/api/geocoding

########################################################
#                         Geocoding                    #
########################################################

### Forward
GET {{ endpoint }}/forward/?address=1600 Pennsylvania Ave NW, Washington DC
### Forward
GET {{ endpoint }}/forward/?address=14 rue de Paradis, 75010 Paris
### Forward
GET {{ endpoint }}/forward/?address=68298 Fairview Place, Huoqiu Chengguanzhen
### Forward
GET {{ endpoint }}/forward/?address=472 Hauk Road, 3859 Nkandla
### Forward
GET {{ endpoint }}/forward/?address=95 Hoard Plaza, H9K Revelstoke
### Forward
GET {{ endpoint }}/forward/?address=139 Bluestem Drive, 97308 CEDEX Cayenne
### Forward
GET {{ endpoint }}/forward/?address=902 Hoepker Parkway, San Miguel


### Reverse
GET {{ endpoint }}/forward/?address=Avenida Mariscal Santa Cruz 1066, La Paz
### Reverse
GET {{ endpoint }}/reverse/?gps=40.7638435,-73.9729691

###########################
#         ERROR           #
###########################

### Forward ERROR
GET {{ endpoint }}/forward/?address=sdgqegezegzer

### Reverse ERROR
GET {{ endpoint }}/reverse/?gps=-90,188

### Reverse
GET {{ endpoint }}/reverse/?gps=2