################################################################################
# Fichier de test des routes HTTP de l'API
# Nécessite l'extension REST Client pour VSCode
# https://marketplace.visualstudio.com/items?itemName=humao.rest-client
################################################################################
@endpoint = http://localhost:{{$dotenv PORT}}/v1/api/place

########################################################
#                       Place                          #
########################################################

### Insert a place
POST {{ endpoint }}/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoxMSwiZmlyc3RuYW1lIjoiYSIsImxhc3RuYW1lIjoiYSIsImVtYWlsIjoiYWFAZ21haWwuY29tIiwicm9sZSI6InVzZXIiLCJub3RpZmljYXRpb24iOnRydWV9LCJpYXQiOjE2NTA0ODIzMzEsImV4cCI6MTY1MDU2ODczMX0.WadisbyFyRS5pm1tFWX8pmtxEGXu9TWS-Upte_kH1dU
content-type: application/json

{
    "name": "At Tony",
    "address": "Bordeaux"
}

### Select all places
GET {{ endpoint }}/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoxMSwiZmlyc3RuYW1lIjoiYSIsImxhc3RuYW1lIjoiYSIsImVtYWlsIjoiYWFAZ21haWwuY29tIiwicm9sZSI6InVzZXIiLCJub3RpZmljYXRpb24iOnRydWV9LCJpYXQiOjE2NTA3Mzk3MzUsImV4cCI6MTY1MDgyNjEzNX0.tK4qgnJ3QwHStWZLLr4RnVM-SqW9YVorX_1GgS1UsW4

### Select a place
GET {{ endpoint }}/16
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoxMSwiZmlyc3RuYW1lIjoiYSIsImxhc3RuYW1lIjoiYSIsImVtYWlsIjoiYWFAZ21haWwuY29tIiwicm9sZSI6InVzZXIiLCJub3RpZmljYXRpb24iOnRydWV9LCJpYXQiOjE2NTA3Mzk3MzUsImV4cCI6MTY1MDgyNjEzNX0.tK4qgnJ3QwHStWZLLr4RnVM-SqW9YVorX_1GgS1UsW4

### Update a place
PATCH {{ endpoint }}/16
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoxMSwiZmlyc3RuYW1lIjoiYSIsImxhc3RuYW1lIjoiYSIsImVtYWlsIjoiYWFAZ21haWwuY29tIiwicm9sZSI6InVzZXIiLCJub3RpZmljYXRpb24iOnRydWV9LCJpYXQiOjE2NTA0ODIzMzEsImV4cCI6MTY1MDU2ODczMX0.WadisbyFyRS5pm1tFWX8pmtxEGXu9TWS-Upte_kH1dU
content-type: application/json

{
    "name": "CHez JUlie",
    "address": "Nîmes"
}

### Delete a place
DELETE {{ endpoint }}/16
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoxMSwiZmlyc3RuYW1lIjoiYSIsImxhc3RuYW1lIjoiYSIsImVtYWlsIjoiYWFAZ21haWwuY29tIiwicm9sZSI6InVzZXIiLCJub3RpZmljYXRpb24iOnRydWV9LCJpYXQiOjE2NTA3Mzk3MzUsImV4cCI6MTY1MDgyNjEzNX0.tK4qgnJ3QwHStWZLLr4RnVM-SqW9YVorX_1GgS1UsW4
