################################################################################
# Fichier de test des routes HTTP de l'API
# Nécessite l'extension REST Client pour VSCode
# https://marketplace.visualstudio.com/items?itemName=humao.rest-client
################################################################################
@endpoint = http://localhost:{{$dotenv PORT}}/v1/api/user

########################################################
#                         User                         #
########################################################

### Vérifier l'authentification d'un user, si c'est ok on me renvoie un token dans le header
### Authorization: Bearer [token]
POST {{ endpoint }}/auth
content-type: application/json

{
    "email": "marcelineajun@gmail.com",
    "password": "xxxx"
}

### Trouver un utilisateur :
GET {{ endpoint }}/profil
Authorization:Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJjbGVhbmVkVXNlciI6eyJpZCI6MjMsImZpcnN0bmFtZSI6Ik1hcmNlbGluZSIsImxhc3RuYW1lIjoiQWp1biIsImVtYWlsIjoibWFyY2VsaW5lYWp1bkBnbWFpbC5jb20iLCJyb2xlIjoidXNlciIsIm5vdGlmaWNhdGlvbiI6dHJ1ZX0sImlhdCI6MTY0OTU4MTEzNSwiZXhwIjoxNjQ5NjY3NTM1fQ.t6BMgeR2qOQruzoKE5xIwRMTLVsck-Z2PLtOjdS4k-c
