################################################################################
# Fichier de test des routes HTTP de l'API
# Nécessite l'extension REST Client pour VSCode
# https://marketplace.visualstudio.com/items?itemName=humao.rest-client
################################################################################
@endpoint = http://localhost:{{$dotenv PORT}}/v1/api/user

########################################################
#                         User                         #
########################################################

### Insert user
POST {{ endpoint }}/
content-type: application/json

{
    "firstname": "b",
    "lastname": "b",
    "email": "bb@gmail.com",
    "password": "xx",
    "role": "user",
    "notification": true
}

### Connect user
### If it's ok you he gets a token in the header => Authorization: Bearer [token]
POST {{ endpoint }}/login
content-type: application/json

{
    "email": "bb@gmail.com",
    "password": "xx"
}

### Disconnect user
GET {{ endpoint }}/logout
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJjbGVhbmVkVXNlciI6eyJpZCI6NiwiZmlyc3RuYW1lIjoiYiIsImxhc3RuYW1lIjoiYiIsImVtYWlsIjoiYmJAZ21haWwuY29tIiwicm9sZSI6InVzZXIiLCJub3RpZmljYXRpb24iOnRydWV9LCJpYXQiOjE2NDk3ODUzNjksImV4cCI6MTY0OTg3MTc2OX0.MPrCqpDI8qKJxr9ZEdvgxL4Le4BWbgVbUo3QA36FHAk

### Select user
GET {{ endpoint }}/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJjbGVhbmVkVXNlciI6eyJpZCI6NiwiZmlyc3RuYW1lIjoiYiIsImxhc3RuYW1lIjoiYiIsImVtYWlsIjoiYmJAZ21haWwuY29tIiwicm9sZSI6InVzZXIiLCJub3RpZmljYXRpb24iOnRydWV9LCJpYXQiOjE2NDk3ODUzNjksImV4cCI6MTY0OTg3MTc2OX0.MPrCqpDI8qKJxr9ZEdvgxL4Le4BWbgVbUo3QA36FHAk

### Update user
PATCH {{ endpoint }}/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJjbGVhbmVkVXNlciI6eyJpZCI6NiwiZmlyc3RuYW1lIjoiYiIsImxhc3RuYW1lIjoiYiIsImVtYWlsIjoiYmJAZ21haWwuY29tIiwicm9sZSI6InVzZXIiLCJub3RpZmljYXRpb24iOnRydWV9LCJpYXQiOjE2NDk3NTMzODYsImV4cCI6MTY0OTgzOTc4Nn0.4woBzYrNhFeBlHVI-vBZZS0IrSaGOPLoFLBs_89PfSE
content-type: application/json

{
    "firstname": "b",
    "lastname": "b",
    "email": "bb@gmail.com",
    "oldPassword": "xx",
    "newPassword": "yy"
}

### Delete user
DELETE {{ endpoint }}/
Authorization:Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJjbGVhbmVkVXNlciI6eyJpZCI6MzEsImZpcnN0bmFtZSI6ImIiLCJsYXN0bmFtZSI6ImIiLCJlbWFpbCI6ImJiQGdtYWlsLmNvbSIsInJvbGUiOiJ1c2VyIiwibm90aWZpY2F0aW9uIjp0cnVlfSwiaWF0IjoxNjQ5Njk2MzY3LCJleHAiOjE2NDk3ODI3Njd9.k1Rgw8aNYA9qT7ipudZZRkIkWBbYlnYWv5HcMPZTrgU
content-type: application/json

{
    "password": "yy"
}

###########################
#         ERROR           #
###########################

### Select user
GET {{ endpoint }}/

### Select user
GET {{ endpoint }}/
Authorization: Bearer qdfgsfds
