################################################################################
# Fichier de test des routes HTTP de l'API
# Nécessite l'extension REST Client pour VSCode
# https://marketplace.visualstudio.com/items?itemName=humao.rest-client
################################################################################
@endpoint = http://localhost:{{$dotenv PORT}}/v1/api/user

########################################################
#                         User                         #
########################################################

### Insert user
POST {{ endpoint }}/
content-type: application/json

{
    "firstname": "b",
    "lastname": "b",
    "email": "bb@gmail.com",
    "password": "xx",
    "role": "user",
    "notification": true
}

### Connect user
### If it's ok you he gets a token in the header => Authorization: Bearer [token]
POST {{ endpoint }}/login
content-type: application/json

{
    "email": "bb@gmail.com",
    "password": "yy"
}

### Disconnect user
GET {{ endpoint }}/logout
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjo2LCJmaXJzdG5hbWUiOiJiIiwibGFzdG5hbWUiOiJiIiwiZW1haWwiOiJiYkBnbWFpbC5jb20iLCJyb2xlIjoidXNlciIsIm5vdGlmaWNhdGlvbiI6dHJ1ZX0sImlhdCI6MTY1MDAyMzA3OCwiZXhwIjoxNjUwMTA5NDc4fQ.B8izslzqmUPLTbZ_HBQ1OgPcPZy2bjYXV55l2dkhZm4

### Select user
GET {{ endpoint }}/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjo2LCJmaXJzdG5hbWUiOiJiIiwibGFzdG5hbWUiOiJiIiwiZW1haWwiOiJiYkBnbWFpbC5jb20iLCJyb2xlIjoidXNlciIsIm5vdGlmaWNhdGlvbiI6dHJ1ZX0sImlhdCI6MTY1MDAyMzA3OCwiZXhwIjoxNjUwMTA5NDc4fQ.B8izslzqmUPLTbZ_HBQ1OgPcPZy2bjYXV55l2dkhZm4

### Update user
PATCH {{ endpoint }}/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjo2LCJmaXJzdG5hbWUiOiJiIiwibGFzdG5hbWUiOiJiIiwiZW1haWwiOiJiYkBnbWFpbC5jb20iLCJyb2xlIjoidXNlciIsIm5vdGlmaWNhdGlvbiI6dHJ1ZX0sImlhdCI6MTY1MDAyMzA3OCwiZXhwIjoxNjUwMTA5NDc4fQ.B8izslzqmUPLTbZ_HBQ1OgPcPZy2bjYXV55l2dkhZm4
content-type: application/json

{
    "firstname": "b",
    "lastname": "b",
    "email": "bb@gmail.com",
    "oldPassword": "xx",
    "newPassword": "yy"
}

### Delete user
DELETE {{ endpoint }}/
Authorization:Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjo2LCJmaXJzdG5hbWUiOiJiIiwibGFzdG5hbWUiOiJiIiwiZW1haWwiOiJiYkBnbWFpbC5jb20iLCJyb2xlIjoidXNlciIsIm5vdGlmaWNhdGlvbiI6dHJ1ZX0sImlhdCI6MTY1MDAyMzMxNCwiZXhwIjoxNjUwMTA5NzE0fQ.fbzQIdXd8RKbehu-V1gxcAAfmFUpqTAoBC-N7lao-30
content-type: application/json

{
    "password": "xx"
}

###########################
#         ERROR           #
###########################

### Select user
GET {{ endpoint }}/

### Select user
GET {{ endpoint }}/
Authorization: Bearer qdfgsfds
